// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName   string                        `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName    string                        `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	MyPatients  *Employee_MyPatients          `protobuf:"bytes,4,opt,name=myPatients,proto3" json:"myPatients,omitempty"`
	CreatedByMe *Employee_PatientsCreatedByMe `protobuf:"bytes,5,opt,name=createdByMe,proto3" json:"createdByMe,omitempty"`
}

func (x *Employee) Reset() {
	*x = Employee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetMyPatients() *Employee_MyPatients {
	if x != nil {
		return x.MyPatients
	}
	return nil
}

func (x *Employee) GetCreatedByMe() *Employee_PatientsCreatedByMe {
	if x != nil {
		return x.CreatedByMe
	}
	return nil
}

type Patient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Salutation string                    `protobuf:"bytes,2,opt,name=salutation,proto3" json:"salutation,omitempty"`
	LastName   string                    `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Employee   *Patient_AssignedEmployee `protobuf:"bytes,4,opt,name=employee,proto3" json:"employee,omitempty"`
	Findings   *Patient_Findings         `protobuf:"bytes,5,opt,name=findings,proto3" json:"findings,omitempty"`
}

func (x *Patient) Reset() {
	*x = Patient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetSalutation() string {
	if x != nil {
		return x.Salutation
	}
	return ""
}

func (x *Patient) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Patient) GetEmployee() *Patient_AssignedEmployee {
	if x != nil {
		return x.Employee
	}
	return nil
}

func (x *Patient) GetFindings() *Patient_Findings {
	if x != nil {
		return x.Findings
	}
	return nil
}

type Finding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Patient           *Finding_PatientRef        `protobuf:"bytes,4,opt,name=patient,proto3" json:"patient,omitempty"`
	SymmptomAreas     []*SymmptomArea            `protobuf:"bytes,5,rep,name=symmptomAreas,proto3" json:"symmptomAreas,omitempty"`
	PainRadar         *PainRadar                 `protobuf:"bytes,6,opt,name=painRadar,proto3" json:"painRadar,omitempty"`
	TrainingSessions  *Finding_TrainingSessions  `protobuf:"bytes,7,opt,name=trainingSessions,proto3" json:"trainingSessions,omitempty"`
	TreatmentSessions *Finding_TreatmentSessions `protobuf:"bytes,8,opt,name=treatmentSessions,proto3" json:"treatmentSessions,omitempty"`
}

func (x *Finding) Reset() {
	*x = Finding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetPatient() *Finding_PatientRef {
	if x != nil {
		return x.Patient
	}
	return nil
}

func (x *Finding) GetSymmptomAreas() []*SymmptomArea {
	if x != nil {
		return x.SymmptomAreas
	}
	return nil
}

func (x *Finding) GetPainRadar() *PainRadar {
	if x != nil {
		return x.PainRadar
	}
	return nil
}

func (x *Finding) GetTrainingSessions() *Finding_TrainingSessions {
	if x != nil {
		return x.TrainingSessions
	}
	return nil
}

func (x *Finding) GetTreatmentSessions() *Finding_TreatmentSessions {
	if x != nil {
		return x.TreatmentSessions
	}
	return nil
}

type SymmptomArea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string  `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	X           float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y           float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Fas         int32   `protobuf:"varint,4,opt,name=fas,proto3" json:"fas,omitempty"`
}

func (x *SymmptomArea) Reset() {
	*x = SymmptomArea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymmptomArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmptomArea) ProtoMessage() {}

func (x *SymmptomArea) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmptomArea.ProtoReflect.Descriptor instead.
func (*SymmptomArea) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *SymmptomArea) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SymmptomArea) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SymmptomArea) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SymmptomArea) GetFas() int32 {
	if x != nil {
		return x.Fas
	}
	return 0
}

type PainRadar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dimensions []*PainRadarDimension `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
}

func (x *PainRadar) Reset() {
	*x = PainRadar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PainRadar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PainRadar) ProtoMessage() {}

func (x *PainRadar) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PainRadar.ProtoReflect.Descriptor instead.
func (*PainRadar) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *PainRadar) GetDimensions() []*PainRadarDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type PainRadarDimension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Degree float32 `protobuf:"fixed32,2,opt,name=degree,proto3" json:"degree,omitempty"`
}

func (x *PainRadarDimension) Reset() {
	*x = PainRadarDimension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PainRadarDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PainRadarDimension) ProtoMessage() {}

func (x *PainRadarDimension) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PainRadarDimension.ProtoReflect.Descriptor instead.
func (*PainRadarDimension) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *PainRadarDimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PainRadarDimension) GetDegree() float32 {
	if x != nil {
		return x.Degree
	}
	return 0
}

type TrainingSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exercises []*Exercise                 `protobuf:"bytes,3,rep,name=exercises,proto3" json:"exercises,omitempty"`
	Finding   *TrainingSession_FindingRef `protobuf:"bytes,4,opt,name=finding,proto3" json:"finding,omitempty"`
}

func (x *TrainingSession) Reset() {
	*x = TrainingSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSession) ProtoMessage() {}

func (x *TrainingSession) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSession.ProtoReflect.Descriptor instead.
func (*TrainingSession) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *TrainingSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingSession) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *TrainingSession) GetFinding() *TrainingSession_FindingRef {
	if x != nil {
		return x.Finding
	}
	return nil
}

type Exercise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reps string `protobuf:"bytes,2,opt,name=reps,proto3" json:"reps,omitempty"`
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetReps() string {
	if x != nil {
		return x.Reps
	}
	return ""
}

type TreatmentSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Findings    *TreatmentSession_Findings   `protobuf:"bytes,4,opt,name=findings,proto3" json:"findings,omitempty"`
	Patient     *TreatmentSession_PatientRef `protobuf:"bytes,5,opt,name=patient,proto3" json:"patient,omitempty"`
}

func (x *TreatmentSession) Reset() {
	*x = TreatmentSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreatmentSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreatmentSession) ProtoMessage() {}

func (x *TreatmentSession) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreatmentSession.ProtoReflect.Descriptor instead.
func (*TreatmentSession) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8}
}

func (x *TreatmentSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TreatmentSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreatmentSession) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TreatmentSession) GetFindings() *TreatmentSession_Findings {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *TreatmentSession) GetPatient() *TreatmentSession_PatientRef {
	if x != nil {
		return x.Patient
	}
	return nil
}

type Employee_MyPatients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackRef *Patient_AssignedEmployee `protobuf:"bytes,1,opt,name=backRef,proto3" json:"backRef,omitempty"`
	Loaded  bool                      `protobuf:"varint,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
	All     []*Patient                `protobuf:"bytes,3,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *Employee_MyPatients) Reset() {
	*x = Employee_MyPatients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee_MyPatients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee_MyPatients) ProtoMessage() {}

func (x *Employee_MyPatients) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee_MyPatients.ProtoReflect.Descriptor instead.
func (*Employee_MyPatients) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Employee_MyPatients) GetBackRef() *Patient_AssignedEmployee {
	if x != nil {
		return x.BackRef
	}
	return nil
}

func (x *Employee_MyPatients) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *Employee_MyPatients) GetAll() []*Patient {
	if x != nil {
		return x.All
	}
	return nil
}

type Employee_PatientsCreatedByMe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackRef *Patient_CreatedByEmployee `protobuf:"bytes,1,opt,name=backRef,proto3" json:"backRef,omitempty"`
	All     []*Patient                 `protobuf:"bytes,3,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *Employee_PatientsCreatedByMe) Reset() {
	*x = Employee_PatientsCreatedByMe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee_PatientsCreatedByMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee_PatientsCreatedByMe) ProtoMessage() {}

func (x *Employee_PatientsCreatedByMe) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee_PatientsCreatedByMe.ProtoReflect.Descriptor instead.
func (*Employee_PatientsCreatedByMe) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Employee_PatientsCreatedByMe) GetBackRef() *Patient_CreatedByEmployee {
	if x != nil {
		return x.BackRef
	}
	return nil
}

func (x *Employee_PatientsCreatedByMe) GetAll() []*Patient {
	if x != nil {
		return x.All
	}
	return nil
}

type Employee_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *Employee `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *Employee_Ref) Reset() {
	*x = Employee_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee_Ref) ProtoMessage() {}

func (x *Employee_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee_Ref.ProtoReflect.Descriptor instead.
func (*Employee_Ref) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Employee_Ref) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee_Ref) GetLoaded() *Employee {
	if x != nil {
		return x.Loaded
	}
	return nil
}

type Patient_Findings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded bool       `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	All    []*Finding `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *Patient_Findings) Reset() {
	*x = Patient_Findings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient_Findings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient_Findings) ProtoMessage() {}

func (x *Patient_Findings) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient_Findings.ProtoReflect.Descriptor instead.
func (*Patient_Findings) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Patient_Findings) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *Patient_Findings) GetAll() []*Finding {
	if x != nil {
		return x.All
	}
	return nil
}

type Patient_AssignedEmployee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *Employee `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *Patient_AssignedEmployee) Reset() {
	*x = Patient_AssignedEmployee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient_AssignedEmployee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient_AssignedEmployee) ProtoMessage() {}

func (x *Patient_AssignedEmployee) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient_AssignedEmployee.ProtoReflect.Descriptor instead.
func (*Patient_AssignedEmployee) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Patient_AssignedEmployee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient_AssignedEmployee) GetLoaded() *Employee {
	if x != nil {
		return x.Loaded
	}
	return nil
}

type Patient_CreatedByEmployee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *Employee `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *Patient_CreatedByEmployee) Reset() {
	*x = Patient_CreatedByEmployee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient_CreatedByEmployee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient_CreatedByEmployee) ProtoMessage() {}

func (x *Patient_CreatedByEmployee) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient_CreatedByEmployee.ProtoReflect.Descriptor instead.
func (*Patient_CreatedByEmployee) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Patient_CreatedByEmployee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient_CreatedByEmployee) GetLoaded() *Employee {
	if x != nil {
		return x.Loaded
	}
	return nil
}

type Finding_PatientRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *Patient `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *Finding_PatientRef) Reset() {
	*x = Finding_PatientRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finding_PatientRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding_PatientRef) ProtoMessage() {}

func (x *Finding_PatientRef) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding_PatientRef.ProtoReflect.Descriptor instead.
func (*Finding_PatientRef) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Finding_PatientRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding_PatientRef) GetLoaded() *Patient {
	if x != nil {
		return x.Loaded
	}
	return nil
}

type Finding_TrainingSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded bool               `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	All    []*TrainingSession `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"` // TODO: backref required! --> in others too
}

func (x *Finding_TrainingSessions) Reset() {
	*x = Finding_TrainingSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finding_TrainingSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding_TrainingSessions) ProtoMessage() {}

func (x *Finding_TrainingSessions) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding_TrainingSessions.ProtoReflect.Descriptor instead.
func (*Finding_TrainingSessions) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Finding_TrainingSessions) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *Finding_TrainingSessions) GetAll() []*TrainingSession {
	if x != nil {
		return x.All
	}
	return nil
}

type Finding_TreatmentSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded bool                `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	All    []*TreatmentSession `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"` // TODO: backref required!
}

func (x *Finding_TreatmentSessions) Reset() {
	*x = Finding_TreatmentSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finding_TreatmentSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding_TreatmentSessions) ProtoMessage() {}

func (x *Finding_TreatmentSessions) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding_TreatmentSessions.ProtoReflect.Descriptor instead.
func (*Finding_TreatmentSessions) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Finding_TreatmentSessions) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *Finding_TreatmentSessions) GetAll() []*TreatmentSession {
	if x != nil {
		return x.All
	}
	return nil
}

type TrainingSession_FindingRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded []*Finding `protobuf:"bytes,2,rep,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *TrainingSession_FindingRef) Reset() {
	*x = TrainingSession_FindingRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingSession_FindingRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSession_FindingRef) ProtoMessage() {}

func (x *TrainingSession_FindingRef) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSession_FindingRef.ProtoReflect.Descriptor instead.
func (*TrainingSession_FindingRef) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6, 0}
}

func (x *TrainingSession_FindingRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingSession_FindingRef) GetLoaded() []*Finding {
	if x != nil {
		return x.Loaded
	}
	return nil
}

// // // // // // //
type TrainingSession_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *TrainingSession `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *TrainingSession_Ref) Reset() {
	*x = TrainingSession_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingSession_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSession_Ref) ProtoMessage() {}

func (x *TrainingSession_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSession_Ref.ProtoReflect.Descriptor instead.
func (*TrainingSession_Ref) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6, 1}
}

func (x *TrainingSession_Ref) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingSession_Ref) GetLoaded() *TrainingSession {
	if x != nil {
		return x.Loaded
	}
	return nil
}

type TrainingSession_Many struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Present bool               `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	All     []*TrainingSession `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"`
}

func (x *TrainingSession_Many) Reset() {
	*x = TrainingSession_Many{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingSession_Many) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSession_Many) ProtoMessage() {}

func (x *TrainingSession_Many) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSession_Many.ProtoReflect.Descriptor instead.
func (*TrainingSession_Many) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6, 2}
}

func (x *TrainingSession_Many) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *TrainingSession_Many) GetAll() []*TrainingSession {
	if x != nil {
		return x.All
	}
	return nil
}

type TreatmentSession_Findings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loaded bool       `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	All    []*Finding `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"` // TODO: backref!
}

func (x *TreatmentSession_Findings) Reset() {
	*x = TreatmentSession_Findings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreatmentSession_Findings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreatmentSession_Findings) ProtoMessage() {}

func (x *TreatmentSession_Findings) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreatmentSession_Findings.ProtoReflect.Descriptor instead.
func (*TreatmentSession_Findings) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8, 0}
}

func (x *TreatmentSession_Findings) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *TreatmentSession_Findings) GetAll() []*Finding {
	if x != nil {
		return x.All
	}
	return nil
}

type TreatmentSession_PatientRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Loaded *Patient `protobuf:"bytes,2,opt,name=loaded,proto3" json:"loaded,omitempty"`
}

func (x *TreatmentSession_PatientRef) Reset() {
	*x = TreatmentSession_PatientRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreatmentSession_PatientRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreatmentSession_PatientRef) ProtoMessage() {}

func (x *TreatmentSession_PatientRef) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreatmentSession_PatientRef.ProtoReflect.Descriptor instead.
func (*TreatmentSession_PatientRef) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8, 1}
}

func (x *TreatmentSession_PatientRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TreatmentSession_PatientRef) GetLoaded() *Patient {
	if x != nil {
		return x.Loaded
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x22, 0xba, 0x04, 0x0a, 0x08, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x40, 0x0a, 0x0a, 0x6d, 0x79, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x4d, 0x79, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0a, 0x6d, 0x79, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x4d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x4d, 0x65, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x4d, 0x65,
	0x1a, 0x8d, 0x01, 0x0a, 0x0a, 0x4d, 0x79, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x3f, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x66,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x1a, 0x7f, 0x0a, 0x13, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x4d, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x61, 0x6c,
	0x6c, 0x1a, 0x44, 0x0a, 0x03, 0x52, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52,
	0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x22, 0xc6, 0x03, 0x0a, 0x07, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x61, 0x6c, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x61, 0x6c, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x41, 0x0a, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x4a, 0x0a,
	0x08, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x1a, 0x51, 0x0a, 0x10, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a,
	0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x1a, 0x52, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x22, 0xb0, 0x05, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x52, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a,
	0x0d, 0x73, 0x79, 0x6d, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x41, 0x72, 0x65, 0x61, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2e, 0x53, 0x79, 0x6d, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x0d, 0x73, 0x79, 0x6d, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x41, 0x72, 0x65, 0x61, 0x73, 0x12, 0x34,
	0x0a, 0x09, 0x70, 0x61, 0x69, 0x6e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x50, 0x61, 0x69, 0x6e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x09, 0x70, 0x61, 0x69, 0x6e, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x12, 0x51, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x10, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x54, 0x0a, 0x11, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x65, 0x61, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x11, 0x74, 0x72, 0x65, 0x61,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x4a, 0x0a,
	0x0a, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x1a, 0x5a, 0x0a, 0x10, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x03, 0x61, 0x6c, 0x6c, 0x1a, 0x5c, 0x0a, 0x11, 0x54, 0x72, 0x65, 0x61, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x12, 0x2f, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x54, 0x72,
	0x65, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x03,
	0x61, 0x6c, 0x6c, 0x22, 0x5e, 0x0a, 0x0c, 0x53, 0x79, 0x6d, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x41,
	0x72, 0x65, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x66, 0x61, 0x73, 0x22, 0x4c, 0x0a, 0x09, 0x50, 0x61, 0x69, 0x6e, 0x52, 0x61, 0x64, 0x61, 0x72,
	0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2e, 0x50, 0x61, 0x69, 0x6e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x44, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x40, 0x0a, 0x12, 0x50, 0x61, 0x69, 0x6e, 0x52, 0x61, 0x64, 0x61, 0x72, 0x44, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x64, 0x65, 0x67,
	0x72, 0x65, 0x65, 0x22, 0x98, 0x03, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x65,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x45, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x09, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73,
	0x12, 0x41, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x66, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x1a, 0x4a, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2c, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x1a,
	0x4b, 0x0a, 0x03, 0x52, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x1a, 0x50, 0x0a, 0x04,
	0x4d, 0x61, 0x6e, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x2e,
	0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x22, 0x32,
	0x0a, 0x08, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65,
	0x70, 0x73, 0x22, 0xf8, 0x02, 0x0a, 0x10, 0x54, 0x72, 0x65, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a,
	0x08, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x54, 0x72,
	0x65, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x42, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x2e, 0x54, 0x72, 0x65, 0x61, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x52, 0x07, 0x70, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x4a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x03, 0x61, 0x6c,
	0x6c, 0x1a, 0x4a, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2c, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x42, 0x26, 0x5a,
	0x24, 0x64, 0x65, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_model_proto_goTypes = []interface{}{
	(*Employee)(nil),                     // 0: objectgraph.Employee
	(*Patient)(nil),                      // 1: objectgraph.Patient
	(*Finding)(nil),                      // 2: objectgraph.Finding
	(*SymmptomArea)(nil),                 // 3: objectgraph.SymmptomArea
	(*PainRadar)(nil),                    // 4: objectgraph.PainRadar
	(*PainRadarDimension)(nil),           // 5: objectgraph.PainRadarDimension
	(*TrainingSession)(nil),              // 6: objectgraph.TrainingSession
	(*Exercise)(nil),                     // 7: objectgraph.Exercise
	(*TreatmentSession)(nil),             // 8: objectgraph.TreatmentSession
	(*Employee_MyPatients)(nil),          // 9: objectgraph.Employee.MyPatients
	(*Employee_PatientsCreatedByMe)(nil), // 10: objectgraph.Employee.PatientsCreatedByMe
	(*Employee_Ref)(nil),                 // 11: objectgraph.Employee.Ref
	(*Patient_Findings)(nil),             // 12: objectgraph.Patient.Findings
	(*Patient_AssignedEmployee)(nil),     // 13: objectgraph.Patient.AssignedEmployee
	(*Patient_CreatedByEmployee)(nil),    // 14: objectgraph.Patient.CreatedByEmployee
	(*Finding_PatientRef)(nil),           // 15: objectgraph.Finding.PatientRef
	(*Finding_TrainingSessions)(nil),     // 16: objectgraph.Finding.TrainingSessions
	(*Finding_TreatmentSessions)(nil),    // 17: objectgraph.Finding.TreatmentSessions
	(*TrainingSession_FindingRef)(nil),   // 18: objectgraph.TrainingSession.FindingRef
	(*TrainingSession_Ref)(nil),          // 19: objectgraph.TrainingSession.Ref
	(*TrainingSession_Many)(nil),         // 20: objectgraph.TrainingSession.Many
	(*TreatmentSession_Findings)(nil),    // 21: objectgraph.TreatmentSession.Findings
	(*TreatmentSession_PatientRef)(nil),  // 22: objectgraph.TreatmentSession.PatientRef
}
var file_model_proto_depIdxs = []int32{
	9,  // 0: objectgraph.Employee.myPatients:type_name -> objectgraph.Employee.MyPatients
	10, // 1: objectgraph.Employee.createdByMe:type_name -> objectgraph.Employee.PatientsCreatedByMe
	13, // 2: objectgraph.Patient.employee:type_name -> objectgraph.Patient.AssignedEmployee
	12, // 3: objectgraph.Patient.findings:type_name -> objectgraph.Patient.Findings
	15, // 4: objectgraph.Finding.patient:type_name -> objectgraph.Finding.PatientRef
	3,  // 5: objectgraph.Finding.symmptomAreas:type_name -> objectgraph.SymmptomArea
	4,  // 6: objectgraph.Finding.painRadar:type_name -> objectgraph.PainRadar
	16, // 7: objectgraph.Finding.trainingSessions:type_name -> objectgraph.Finding.TrainingSessions
	17, // 8: objectgraph.Finding.treatmentSessions:type_name -> objectgraph.Finding.TreatmentSessions
	5,  // 9: objectgraph.PainRadar.dimensions:type_name -> objectgraph.PainRadarDimension
	7,  // 10: objectgraph.TrainingSession.exercises:type_name -> objectgraph.Exercise
	18, // 11: objectgraph.TrainingSession.finding:type_name -> objectgraph.TrainingSession.FindingRef
	21, // 12: objectgraph.TreatmentSession.findings:type_name -> objectgraph.TreatmentSession.Findings
	22, // 13: objectgraph.TreatmentSession.patient:type_name -> objectgraph.TreatmentSession.PatientRef
	13, // 14: objectgraph.Employee.MyPatients.backRef:type_name -> objectgraph.Patient.AssignedEmployee
	1,  // 15: objectgraph.Employee.MyPatients.all:type_name -> objectgraph.Patient
	14, // 16: objectgraph.Employee.PatientsCreatedByMe.backRef:type_name -> objectgraph.Patient.CreatedByEmployee
	1,  // 17: objectgraph.Employee.PatientsCreatedByMe.all:type_name -> objectgraph.Patient
	0,  // 18: objectgraph.Employee.Ref.loaded:type_name -> objectgraph.Employee
	2,  // 19: objectgraph.Patient.Findings.all:type_name -> objectgraph.Finding
	0,  // 20: objectgraph.Patient.AssignedEmployee.loaded:type_name -> objectgraph.Employee
	0,  // 21: objectgraph.Patient.CreatedByEmployee.loaded:type_name -> objectgraph.Employee
	1,  // 22: objectgraph.Finding.PatientRef.loaded:type_name -> objectgraph.Patient
	6,  // 23: objectgraph.Finding.TrainingSessions.all:type_name -> objectgraph.TrainingSession
	8,  // 24: objectgraph.Finding.TreatmentSessions.all:type_name -> objectgraph.TreatmentSession
	2,  // 25: objectgraph.TrainingSession.FindingRef.loaded:type_name -> objectgraph.Finding
	6,  // 26: objectgraph.TrainingSession.Ref.loaded:type_name -> objectgraph.TrainingSession
	6,  // 27: objectgraph.TrainingSession.Many.all:type_name -> objectgraph.TrainingSession
	2,  // 28: objectgraph.TreatmentSession.Findings.all:type_name -> objectgraph.Finding
	1,  // 29: objectgraph.TreatmentSession.PatientRef.loaded:type_name -> objectgraph.Patient
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymmptomArea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PainRadar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PainRadarDimension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exercise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreatmentSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee_MyPatients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee_PatientsCreatedByMe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient_Findings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient_AssignedEmployee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient_CreatedByEmployee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finding_PatientRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finding_TrainingSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finding_TreatmentSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingSession_FindingRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingSession_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingSession_Many); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreatmentSession_Findings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreatmentSession_PatientRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
